# Generated by Django 3.2.9 on 2021-11-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='house_transactions',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('zipcode', models.CharField(max_length=10)),
                ('property_type', models.CharField(max_length=1)),
            ],
        ),
    ]
